### ISSUE TITLE
Equations in the paper

### ISSUE THREAD

**Issue by xianrui-luo** [yzhao520/CPP#1]
Hi, I am not familiar with 3D projection, I wonder if there is any reference regarding to the equation 7 in your paper? I cannot find where to calculate $V_{proj}$

![image](https://user-images.githubusercontent.com/44058627/171425485-5b44d0db-a7b9-4462-9285-fb3a55808cc8.png)

**Comment by yunhan-zhao** [comment]
v_{proj} is just vector [0, 0, 1] and extract the last dimension (z axis) in the 3d point.

**Comment by xianrui-luo** [comment]
Thank you for replying.
